name: price_flow_project
description: "Price Flow App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  http: ^1.2.1
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.2.16
  awesome_snackbar_content: ^0.1.3
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  cached_network_image: ^3.3.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.1.1
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  card_loading: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  logging: ^1.1.0
  build_runner_core: ^7.1.2
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/user/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"